-- Add users
insert into users (user_first_name, user_last_name, user_location, user_name, user_email, user_password, user_role) values ('Francisco', 'Traquete', 'location', 'frant7', 'francisco@gmail.com', 'test123', 'user');
insert into users (user_first_name, user_last_name, user_location, user_name, user_email, user_password, user_role) values ('Maria', 'Martins', 'location', 'maria', 'maria@gmail.com', 'test123', 'admin');
insert into users (user_first_name, user_last_name, user_location, user_name, user_email, user_password, user_role) values ('Mario', 'Nascimento', 'location', 'darkarp', 'mario@gmail.com', 'test123', 'user');
insert into users (user_first_name, user_last_name, user_location, user_name, user_email, user_password, user_role) values ('Afonso', 'Goulart', 'location', 'afih', 'afonso@gmail.com', 'test123', 'user');
insert into users (user_first_name, user_last_name, user_location, user_name, user_email, user_password, user_role) values ('Roberta', 'Santos', 'location', 'robi', 'roberta@gmail.com', 'test123', 'user');
insert into users (user_first_name, user_last_name, user_location, user_name, user_email, user_password, user_role) values ('João', 'Garcia', 'location', 'johnny', 'joao@gmail.com', 'test123', 'user');
insert into users (user_first_name, user_last_name, user_location, user_name, user_email, user_password, user_role) values ('Miguel', 'Bernardo', 'location', 'michael', 'michael@gmail.com', 'test123', 'user');
insert into users (user_first_name, user_last_name, user_location, user_name, user_email, user_password, user_role) values ('Laura', 'Martins', 'location', 'lala', 'laura@gmail.com', 'test123', 'user');
insert into users (user_first_name, user_last_name, user_location, user_name, user_email, user_password, user_role) values ('Pedro', 'Costa', 'location', 'costa', 'pedro@gmail.com', 'test123', 'user');
insert into users (user_first_name, user_last_name, user_location, user_name, user_email, user_password, user_role) values ('Antónia', 'Manaia', 'location', 'tozita', 'antonia@gmail.com', 'test123', 'user');